{{-  if and .Values.sasl.plain.enabled (not (hasKey .Values.sasl.plain "useExistingSecret")) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "schema-registry.fullname" . }}-sasl-plain-secret
  labels:
    app: {{ template "schema-registry.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  sasl-password: {{ .Values.sasl.plain.password | b64enc }}
{{- end -}}
